name: text_analytics
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - gensim>=4.1.2
  - scikit-learn
  - datasets
  - ipywidgets
  - nltk
  - matplotlib
  - pytorch
  - transformers
  - scipy
  - python-crfsuite
  - accelerate
prefix: /Users/es1595/opt/anaconda3/envs/data_analytics
